### ISSUE TITLE
Implement Theme for Dark Mode

### ISSUE THREAD

**Issue by SaiDheerajPeketi** [ContriHUB/Just-Share#1]
# 🚀Feature Request
Implementation of Theme for Dark Mode

### Expected behavior
An aesthetic Dark Mode with a theme and drawables similar to the theme used in Light Mode.

### Current behavior
Uses Default Dark Theme and some customised Theme colors in Dark Mode that don't go well with the App's Theme in Light Mode.

### Step to reproduce
Turn Dark Mode On after running the application.

### Possible Solution
Modify the Colors and Drawables being utilised  when application is being used in dark mode.

### Why is this feature important to you?
This feature give a sense of uniformity allowing the app to be usable in dark mode too.

**Comment by AGNIHOTRIMAHI** [comment]
Hey!I am working on the issue

**Comment by SaiDheerajPeketi** [comment]
Comment on Github Issue

**Comment by ShivaniSaini123** [comment]
I am interested in doing this. Should I start?

**Comment by ShivaniSaini123** [comment]
This project is in Kotlin, but I don't know the language. I am familiar with React and CSS. Can I still contribute to improving this project?

**Comment by SaiDheerajPeketi** [comment]
Yes, you can try learning it on the go, if you are interested.

**Comment by aachintya** [comment]
Hi @ShivaniSaini123 . How will you implement dark theme. I need to know because i am working on a follow up issue requires to know your implmentation.

**Comment by ShivaniSaini123** [comment]
I don't know kotlin,but I implement before in react

**Comment by aachintya** [comment]
Ok i'll wait for 1 day

**Comment by ShivaniSaini123** [comment]
You can start your work; I am working on another issue assigned by the seniors

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi can you assign me this issue. i know kotlin

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi please add hacktoberfest label to this issue

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi please review my PR

**Comment by SaiDheerajPeketi** [comment]
I've added bonus for this issue, if you implement theme based icon

**Comment by SaiDheerajPeketi** [comment]
I've added bonus for this issue, if you implement theme based icon
