### ISSUE TITLE
Implement Settings View

### ISSUE THREAD

**Issue by SaiDheerajPeketi** [ContriHUB/Just-Share#2]
# 🚀Feature Request

### Description
The feature requested is to implement a settings feature that allows users to save preferences related to the interface theme (dark mode, light mode), the default storage location for files and the default file transfer mode. This setting would help users personalize their experience with the app based on their preferences and work environment.

### Expected behavior
Populated and Fully Functional Settings View.

### Current behavior
The Settings View is completely empty.

### Steps to reproduce

1. Launch the App.
2. Click on Settings in the Navigation Bar. This would lead you to the empty composable which should be populated and added with functionality.

### Possible Solution
Using Shared Preferences to store the User Preferences and tweak the app logic accordingly,
**Theme Preferences**: A toggle to switch between dark mode and light mode, with the choice being saved as the default for future sessions. These should be changed in the theme and the composables should be tweaked accordingly to handle the dark mode change accordingly.
**Default Storage Location**: A setting that allows users to specify their preferred directory for saving files, which will be remembered by the app. This preference should be checked to change the storage location accordingly at runtime while writing to disk.
**Default File Transfer Mode**:A toggle switch between Bluetooth and Wifi Direct which would set the user preference on the launching view which is currently defaulted to Bluetooth.

### Why is this feature important to you?
This feature is essential because users frequently switch between dark mode and light mode depending on their surroundings, such as low-light or bright environments. Additionally, allowing users to select a default storage location can streamline workflows, as they won't need to manually select a location each time they save a file. It also enhances user experience by offering more control over how they interact with the application.

**Comment by aachintya** [comment]
I am interested in Trying. Have requested on contrihub website.

**Comment by aachintya** [comment]
I guess dark theme is not yet implemented. Is it assigned to somone? If yes then i will have to wait to know whether he is using materialstheme or something else. I'll wait till he submits his task and will complete my work after him

**Comment by SaiDheerajPeketi** [comment]
You can try communicating with them through comments ig

**Comment by SaiDheerajPeketi** [comment]
@aachintya I think u can try implementing the dark theme part assuming it will be using material theme itself

**Comment by aachintya** [comment]
ok sir. i'll try

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi can you assign me this issue.

**Comment by SaiDheerajPeketi** [comment]
@RITIK-CHAUDHRY Request through contrihub website, i've accepted your request for 1st issue

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi I HAVE SENT YOU THE REQUEST PLEASE ASSIGN ME NOW THIS ISSUE SO THAT I CAN START WORKING ON THIS. ALSO ADD HACKTOBERFEST LABEL

**Comment by SaiDheerajPeketi** [comment]
@RITIK-CHAUDHRY  Do you want me to assign this now or after the PR of 1st issue is closed?

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi i will start working when you assign me

**Comment by EvilSprit** [comment]
@RITIK-CHAUDHRY Do you have any UI which I can refer to implement the Settings? 

Tagging @SaiDheerajPeketi for visibility

**Comment by RITIK-CHAUDHRY** [comment]
@EvilSprit i am assigned on this project and i am doing work on this

**Comment by EvilSprit** [comment]
@RITIK-CHAUDHRY I had implemented a lot things do you want to contribute together?

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi sir as dark theme is not yet merged so i had passed the code for dark theme once it will be merged i will make the settings for dark mode too.
also sir i have an idea do i add a button through which user can switch between dark mode and light mode(for bonus marks 😅)
